### ISSUE TITLE
間違えてキャンセル処理してしまいました。

### ISSUE THREAD

**Issue by YoshikiShibata** [yamayamaKo/portofolio#1]
@yamayamaKo 山田さん、間違えて、オンライン読書会をキャンセル処理してしまいました。私からのメッセージは無視してください。このissueを読んだら、closeしておいてください。

**Comment by yamayamaKo** [comment]
@YoshikiShibata 
メッセージありがとうございます。内容確認致しました。

ちょうど先程、私から間違えてキャンセルされている旨のメッセージを送信してしまいました。
